version: "3"
networks:
  default:
    external:
      name: pacifica_default
services:
  drupalamqp:
    image: rabbitmq:3.7
  notifyrouter:
    build:
      context: docker/notify-router
    links:
      - drupalamqp
    environment:
      HOST: drupalamqp
  drupaldb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
  drupal:
    build:
      context: .
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    links:
      - drupaldb
    ports:
      - "9080:80"
      - "2222:22"
    command: /lib/systemd/systemd
